version: "3.8"
services:

  couchbase-server:
    build: ./couchbase-server
    ports:
      - 8091-8096:8091-8096
      - 11210:11210
    environment:
      - CLUSTER_NAME=${COUCHBASE_CLUSTER_NAME}
      - COUCHBASE_ADMINISTRATOR_USERNAME=${COUCHBASE_ADMINISTRATOR_USERNAME}
      - COUCHBASE_ADMINISTRATOR_PASSWORD=${COUCHBASE_ADMINISTRATOR_PASSWORD}
      - COUCHBASE_BUCKET=${COUCHBASE_BUCKET}
      - COUCHBASE_RBAC_USERNAME=${COUCHBASE_RBAC_USERNAME}
      - COUCHBASE_RBAC_PASSWORD=${COUCHBASE_RBAC_PASSWORD}
      - COUCHBASE_RBAC_NAME=${COUCHBASE_RBAC_NAME}
      - COUCHBASE_BUCKET_RAMSIZE=${COUCHBASE_BUCKET_RAMSIZE}
      - COUCHBASE_RAM_SIZE=${COUCHBASE_RAM_SIZE}
      - COUCHBASE_INDEX_RAM_SIZE=${COUCHBASE_INDEX_RAM_SIZE}
    hostname: couchbase-server
    container_name: couchbase-server
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - workshop
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/init-cbserver.sh"

networks:
  workshop:
    driver: bridge
